README.MD
Added CSV49: Comma Separated Values For Nigeria.
=> Added CSV49

README.MD
Helpful sails.js library with active usage on **npm**
See [sails-hook-jsonwebtoken](https://www.npmjs.com/package/sails-hook-jsonwebtoken) and [sails-hook-datatable](https://www.npmjs.com/package/sails-hook-datatable)
=> added 2 sails.js helpful modules

README.MD
Hey,
I just added an Atom theme I built to the list. Thanks 👍🔥.
=> Added Atom Material Palenight Syntax :ok_hand:

README.MD
An api for basic information about all 36 states in Nigeria available here
https://nigerian-states-info.herokuapp.com/
=> Added nigerian states api

README.MD
Added Laravel-Slack package by goodnesskay to the repository
=> Added Laravel-Slack package by goodnesskay

README.MD
Added a Made-In-Nigeria Project (localGoogle)
=> updated README

README.MD
=> Updates adding a new project

README.MD
Added web-crawljs by [Badewa Kayode](https://github.com/kayslay/web-crawljs)
=> Added web-crawljs

README.MD
Hi @acekyd,
Great job here 👍❤️. I just added to the list my newly published VSCode theme,  [Material Palenight Theme](https://marketplace.visualstudio.com/items?itemName=whizkydee.material-palenight-theme). I think you should try it out too! It's definitely one of the best themes.
Also, I changed the profile link of my Atom theme from GitHub to my twitter handle 😏.
Much thanks!
=> Added VSCode Material Palenight Theme + Updated details of my Atom theme

README.MD
Hello! I added a tiny web application to the list
=> added StudyLog

README.MD
add Laravel Payant by olaoluwa-98 to README.md
=> add Laravel Payant by olaoluwa-98

index.html, src/css/app.css
I visited the site yesterday on my mobile device, and discovered the site isn't responsive. So, I took it upon myself today to fix the responsiveness and also continually contribute to the project.
=> Fixed the responsiveness of the site

README.MD, src/js/md2html.js
Fix for Issue #51 
Might take clearing of cache for changes to take effect
=> Fix for #51

README.MD
Reverts acekyd/made-in-nigeria#54
=> Revert "add Webpack2-React Starterkit to list"

README.MD
A client library for moneywave-api
=> Added a repo - moneywave-nodejs by @CodebyOmar

README.MD
Had to update dead links with active links.
=> Update Information in README.MD

README.MD
Ordered N-projects
Fixed naija_pikin repo url
Added github url for Nojs author
=> Added naija_pikin and eneyi projects

README.MD
1. The creator of 'Atom Material Palenight Syntax' and 'VSCode Material Palenight Theme' has changed his twitter handle from @whizkydee to @mrolaolu, so i helped update that 👍🏿
2. Added Random48LawsOfPower by AceKYD 
3. Added IGdm by teddyskillz2
=> Updated twitter handle and Added more itmes

README.MD
It's a library by my teammate Kizito
=> Added Time by Kizito Nwose

contributing.md
Made the smileys in contributing.md appear appropriately using the relevant markdown
=> Adjusted the smileys in contributing.md

README.MD
Breadcrumb for Codeigniter - A codeigniter library for generating Breadcrumb
=> Added a codeigniter library

README.MD
- Added angular4-paystack
- Reordered angular2-sails-starter
=> Added Angular4-paystack

README.MD
I just added Frontend-App-Starter to the list.
=> Added Frontend-App-Starter to the list.

README.MD
Added Shutdown - A lightweight android library that handles the closing of your app interactively.
=> Add Shutdown android library

README.MD
Hi, i added my small project to the list.
=> Added favico-generator to the list

README.MD
A simple npm package for Nigeria States And Local Governments
=> Add Naija State And Local Government

README.MD
I just created the library to help people get the base 64 format of the files they upload.
=> Added Fuctbase64, a library I created to convert file to base64

README.MD
Added [generator-nestjs-app](https://github.com/ashinzekene/generator-nestjs-app)
=> Added generator-nestjs-app

README.MD
[Added VSCode NestJS Snippets](https://github.com/ashinzekene/vscode-nestjs-snippets)
=> Added VSCode NestJS Snippets

README.MD
Project was transferred to a new repository, so, project URL and other information were updated
=> Updated Repo URL, and author twitter details

README.MD
Added an entry for a browser extension
=> Added a new entry to Made-in-Nigeria: A browser extension called Ijeawele. 

README.MD
The first is an application state manager and the second is a library for detecting the rendering engine of any browser on any device.
=> Adding 2 good projects by @isocroft

README.MD
Reverts acekyd/made-in-nigeria#105 as it doesn't fully satisfy the instructions listed here https://github.com/acekyd/made-in-nigeria/blob/master/contributing.md
=> Revert "Added Icon Search"

README.MD
@codehakase ... Project now has up to 5 stars.
=> Add ci-toastr (reached 5 stars)

README.MD
=> Added `NettyFinder` to Made-In-Nigeria Projects

README.MD
I changed the name of a project from `NettyFinder` to `Netty-Finder` to fix #119
=> Modification to fix #119

README.MD
=> Remove projects not stratifying the requirements on the contributions guide, fixes #113

README.MD
- Add new projects to the repository
- Update already existing project
=> patch: add new projects

README.MD
Add a project I worked on for Employee Management following the Multi-tenant Approach.
Built with Django & Vuejs
=> Added Multitenant Employee Manager Project

README.MD
Added chakra UI to the Made in Nigeria list. Find it at the last spot under alphabet C.
Chakra UI is a simple, modular and accessible component library that gives you all the building blocks you need to build your React applications.
=> added chakra ui to MIN list under alphabet C

README.MD
The PR have blink alert added to the list.
=> #Added Blink Alert - a chrome extension

README.MD
Added WhatsApp Dictionary Bot  :zap:
=> Added WhatsApp Dictionary Bot

contributing.md
Increased requirements for contributions.
=> Updated stars requirement

README.MD
Added entry for [Githint GitHub bot](https://github.com/Chieze-Franklin/githint-bot)
=> Added Githint GitHub bot

README.MD
This pull request removes the duplicate entry for "Netty Finder".
=> Remove Duplicate Entry - Issue #152

README.MD
Added 2 projects from @shalvah and one project from @isocroft and @devamaz ( @stitchng )
=> Update README.MD to include 3 projects

README.MD
=> Add Laravel-SMS

README.MD
- Currency-thousand-separator
- React Google Places API library
- Quicksi
=> add one open-source project to the list

README.MD
=> Fix typo about "twitter"

README.MD
This PR adds 4 projects whom are eligible ( 10 stars ) and are in active use even today.
=> Add 4 Projects In Active Use

README.MD
I added two great and novel packages created by 2 Open Source Developers. I also updated the Twitter details of **Mannaseh Mmadu** whose project **[Search Engine Parser](https://github.com/bisoncorps/search-engine-parse)** which is already listed on this repo had a non-existing twitter page for the author which i updated.
The 2 packages added meet the criteria of the minimum amount of stars.
=> Added 2 Novel Packages

README.MD
react native woocommerce api library - A wrappper that connects react Native to the WooCommerce API
=> add react native woocommerce library

README.MD
- * [Broad-state](https://github.com/adenekan41/broadstate) - Easy state manager for state values from one component to the other with useState and React Hooks in < 1KB!. **By [@codewonders](https://twitter.com/code_wonders)**
- * [Piggment](https://github.com/adenekan41/piggment) - A curated collection of amazingly colored gradients for designers, developers and art makers over the world. **By [@codewonders](https://twitter.com/code_wonders)**
- * [Urley](https://github.com/adenekan41/urley) - A cross-platform library with a collection of handy utilites to work with URLs. **By [@codewonders](https://twitter.com/code_wonders)**
- * [Unitcss](https://github.com/adenekan41/unitcss) - A cli tool to convert css units in your file, helps you swiftly convert units / mesurements in your file or …
=> Added packages by codewonders

README.MD
Added amazon pay ruby SDK  built by @bytenaija to the list of made in N…
=> Added amazon pay ruby SDK 

README.MD
PlugMan 🚀🚀
Postman... but for socket connections.
=> Added plugman

README.MD
This PR added use-global-hook and use-cookie npm packages and I also edited my existing details.
=> Add use-global-hook and use-cookie

README.MD
Added laravel-spam-email package to README.md
=> Added Laravel-Spam-Email package

README.MD
DevOps toolkit is a tool that helps you setup your Cloud & DevOps development environment quickly and easily.
=> added devops-toolkit

README.MD
I made a change to the  Readme file on line 285,(alphabet Y section). please kindly review
=>  I'm adding 'Yorlang' on line 285  as one of the made in Nigeria tool

README.MD
A Twitter bot, explaining and simplifying web3 terms to everyone! [Web3terms](https://twitter.com/web3terms)
=> Add Web3terms

README.MD
> A dead-simple paper for keeping notes.
Notes is a simple notes taking app that focuses on simplicity to reduce distractions.
=> added notes to list of projects

README.MD
Added the following Laravel packages by @victorybiz 
- [Laravel Simple Select](https://github.com/victorybiz/laravel-simple-select)
- [Laravel Telephone Input](https://github.com/victorybiz/laravel-tel-input)
- [Laravel Crypto Payment Gateway](https://github.com/victorybiz/laravel-crypto-payment-gateway) - Forked by [GoUrl.io](https://github.com/cryptoapi?tab=repositories) as the official laravel integration.
=> Added Laravel packages by @victorybiz 

src/components/layout.js, src/components/menu.js, src/pages/index.js, src/theme/index.js
=> Update components structure

README.MD
- I removed the gettype package by Uche Jude, the link to the repository no longer exists.
- I added a dotnet package - watchDog by Izy pro.
=> Added a package, and removed another package that no longer exists

README.MD
Does this make qualify for Made In Nigeria? Not sure.
=> Add markdown badges by @ileriayooo

src/components/Hero.js, src/components/NavBar.js, src/components/SearchProject.js, src/pages/index.js
- Hero section design.
- Extracted the Search Projects input field in the mobile dropdown menu into a separate component, then reused it on the Hero section.
- The result of the Hero section on mobile might be slightly different from the design. Still researching if it's possible to use transform on background images with the shorthand command without affecting the entire container. Open to ideas and assistance on this.
=> Hero Section

src/components/ProjectCard.js
- Added the share modal feature to the ProjectCard component
- The design is not pixel-perfect yet because Chakra's default modal sizes defer slightly and might need a bit of manual configuration before achieving the exact design. This can be discussed later.
- Let me know what you think.
=> Project card modal initial design

src/components/Hero.js, src/components/ProjectsHero.js, src/components/SearchProject.js, src/pages/index.js
- Created the Projects Hero component.
- Modified SearchProjects component to accept `mobileWidth` and `desktopWidth` as props for better flexibility and reusability
=> Hero section for the projects page

src/components/BlogHero.js, src/components/SearchArticles.js, src/pages/index.js
- Created BlogHero following the same format as projects hero.
- Created Search Articles child component.
=> BlogHero & SearchArticles components

src/components/AboutHero.js, src/pages/index.js
Fully responsive about page hero section.
=> Hero Section for the About page

src/components/BuiltByNigeriansAbout.js, src/components/Buttons/ViewGithubRepo.js, src/pages/index.js
- Created `ViewGithubRepo` button component.
- Fully responsive design of the Built by Nigerians section of the About page.
=> Built by Nigerians Section of the About Page

src/pages/index.js
- Rendered each component in their respective Boxes in `pages/index.js`
=> Render Issue Fix

src/pages/example.js
Since we have a lot of components now, it's time to start putting them in the right places.
* I moved over all the examples and use of the components to /example.js
* Cleaned up the index file to start to resemble the homepage.
=> Clean up components

README.MD
=> docs: update README.md to reflect esgit

README.MD
Python package for Webscraping with GPT3
=> Added Blackmaria

README.MD
Clean up of current repositories and projects currently on the list:
Adding a deprecated flag in front of repositories last updated pre-2020
=> feat: Add deprecated flag to outdated repos

app/about/page.js, app/assets/team.json, app/components/TeamCard.js, app/components/pages/AboutPage.js
=> About page

app/components/AlphabetFilter/AlphabetFilterNormal.js, app/components/pages/ProjectsPage.js
=> Alphabet filter

README.MD
Added PageCarton as a tool built by a Nigerian. PageCarton is a tool to build a great website in 2 hrs or less - fast & easy to use. Automate things programmers & designers spend several hours putting together.
=> Added PageCarton

app/components/AlphabetFilter/AlphabetFilter.js, app/components/Buttons/ExploreProjects.js, app/components/Hero.js, app/components/NavBar.js, app/components/ProjectsHero.js, app/components/SearchProject.js, app/components/pages/ProjectsPage.js, app/components/pages/components/homepage-client.js
Implement projects search from the homepage
=> project search app scope

app/components/NavBar.js, app/components/pages/HomePage.tsx, app/components/pages/ProjectsPage.js, app/components/pages/components/homepage-client.js, app/projects/page.js, app/projects/state/projects-store.ts, app/store/index.ts, package-lock.json, package.json
Figuring this out was quite tricky because of the limitation of RSCs when it comes to client-side state. But, the idea of passing data through props &mdash; as Segun suggested &mdash; rescued me. 
So for now @acekyd, I have a demo. All the projects are in a store. At first, it was only present on the project's route, so I had to move it to the homepage since that'll be a landing zone for everyone who visits madeinnigeria.dev. 
To test it, I tried accessing the store from the navbar component &mdash way up in the component tree &mdash; and logged the value to the console. 
You can try testing it in the other routes too. When you see this, I'd love you to explain #268 again to me. I have a shallow understanding of what it seemed to explain.
=> feat: persist projects to a store (demo)

app/components/ProjectCard.js, app/components/pages/ProjectsPage.js
=> Project Card

app/components/Blog/ArticleCard.tsx, app/components/ProjectCard.js, app/components/pages/ProjectsPage.js, app/components/pages/components/homepage-client.js
=> Responsiveness checklist

README.MD
This PR adds [Goignore](https://github.com/hacktivist123/goignore) to the list of projects
=> Add Goignore to the list

.editorconfig, README.MD
**Title:**
Rearrange the README B section alphabetically and format it using Prettier.
This PR aims to rearrange the B section alphabetically and format it using Prettier for easy readability.
- Update README.MD
=> Rearrange the README B section alphabetically and format it using Prettier.

README.MD
**Title:**
add fastapi-mongo by kvng_zeez
add fastapi-mongo by kvng_zeez
- Update README.MD
=> add fastapi-mongo by kvng_zeez

app/components/Blog/ArticleCard.tsx, app/components/Blog/BlogPost.tsx
=> fix: image shrinkage

app/components/AlphabetFilter/AlphabetFilter.js, app/components/pages/ProjectsPage.js
=> feat: fix alphabet filter to top on scroll on mobile devices

app/components/Blog/ArticleList.tsx, app/components/BlogHero.tsx, app/components/ProjectsHero.tsx, app/components/featured-articles/feature-article-main.tsx, app/components/featured-articles/index.tsx, app/components/pages/ProjectsPage.js, app/components/pages/components/homepage-client.js
=> fix(ui): refactor layout styles

app/components/Blog/BlogPost.tsx
Fixes: https://github.com/acekyd/made-in-nigeria/issues/300
=> fix: update breakpoint on creator page that breaks UI on larger screens

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/improvement.yml, .github/PULL_REQUEST_TEMPLATE.md, app/components/ProjectCard.js, app/utils/projects.ts
Fixes: https://github.com/acekyd/made-in-nigeria/issues/299.
In this PR, I add the exact same template I use on https://github.com/rotimi-best/classroomio.
- To view the issue template, visit here: https://github.com/rotimi-best/classroomio/issues/new/choose
- To view the PR template, visit here: https://github.com/rotimi-best/classroomio/pull/193
=> ci: add PR and issue templates

.github/PULL_REQUEST_TEMPLATE.md, app/creators/articles/omolara-adejuwon.mdx, app/utils/projects.ts
This PR:
- updates the project's data source to the local file
- fixes an error in Omolara's excerpt 
- and updates the PR template.
It either works or it doesn't. Projects are fetched successfully ✅
=> Quick refactors 

app/utils/projects.ts
=> [Bug] fix page reloading on projects

README.MD
This PR adds the Startease CLI project to the curated list of Made In Nigeria projects. The Startease CLI is an innovative command-line tool designed to streamline and enhance the development workflow for developers. This addition aims to showcase the ingenuity and skill of Nigerian developers in creating tools that cater to specific development needs.
- Test A
-  Navigate to the Projects page and verify that the Startease CLI project appears in the list. Check for correct project name, description, and GitHub link.
- Test B
- Use the search functionality on the Projects page to search for "Startease CLI" and ensure the project is filtered and displayed correctly
=> add startease cli to project list

README.MD
- Adds TransformersPHP by @CodeWithKyrian
=> docs: add TransformersPHP by @CodeWithKyrian

app/utils/projects.ts
Fixes #315 
@acekyd, I noticed that this issue was our own doing. I had to inspect the page in pro, and it refreshes every `5000ms`, which was what we've asked it to do, literally. 
I wondered why it worked formerly &mdash; no refreshes when it was formerly `3000ms`. The only hypothesis I have now is because the former implementation wasn't extending [React's cache](https://react.dev/reference/react/cache). Now that the request in the hook is memoized, there's no need for the revalidation, I guess. 
Eventually, I had to set `revalidate` to false. 
This PR [Fixes #315
[You can check this version I deployed on netlify](https://madein9ja.netlify.app/projects)
=> chore: set revalidate to false

README.MD
This PR adds `ngyn.rs` web framework to README.md
=> docs: Add `ngyn.rs` web framework

README.MD
Adds [Meethub](https://github.com/iyanuashiri/meethub) by Iyanu Ashiru to the list 
Project Details:
- Name: Meethub
- Description: A web application for organizing meetups
- GitHub: https://github.com/iyanuashiri/meethub
- Author: @iyanuashiri
Changes:
- Added entry under the 'M' section
- Maintained alphabetical ordering
- Followed existing format for project listings
- Test A
- Test B
=> Chore: Add Meethub to project listing under 'M'

README.MD
This PR adds [colima](https://github.com/abiosoft/colima) by abiosoft to the README.md
- Check the README.md to verify the formatting is correct and it is in the correct alphabetical order
=> chore: add colima by abiosoft

README.MD
This PR Adds Python WhatsApp bot to the list in ReadMe
=> docs: Added Python WhatsApp bot

README.MD
This PR adds [Stream2Peer](https://github.com/tobySolutions/stream2peer) by Tobiloba, Emmanuel and Jumo to the README.md
- Check the README.md to verify the formatting is correct and it is in the correct alphabetical order
=> feat: add stream2peer to showcase projects

README.MD
This PR adds the narrative generator built by Moses Odutusin to the made in Nigeria project.
- Test A
- Test B
=> feat: add narrative generator to made in Nigeria project

README.MD
This PR [Fixes # (place issue number here without bracket)]
- Test A
- Test B
=> feat: Added Dunsin project to the list of projects
